<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Name>SavorHub</Name>
    <AssemblyName>SavorHub.Web</AssemblyName>
    <RootNamespace>SavorHub.Web</RootNamespace>
    <UserSecretsId>b70a1b09-dc11-40f8-b006-e550a22edf4c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Pages\Admin\Favorites\" />
    <Folder Include="wwwroot\images\menuItems\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="NuGet.Packaging" Version="7.9.0" />
    <PackageReference Include="NuGet.Protocol" Version="7.9.0" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
    <PackageReference Include="Stripe.net" Version="52.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SavorHub.Data\SavorHub.Data.csproj" />
    <ProjectReference Include="..\SavorHub.Utilities\SavorHub.Utilities.csproj" />
  </ItemGroup>

</Project>
