<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Name>SavorHub.Utility</Name>
    <AssemblyName>SavorHub.Utility</AssemblyName>
    <RootNamespace>SavorHub.Utility</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.5" />
  </ItemGroup>

</Project>
