<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Name>SavorHub</Name>
    <AssemblyName>SavorHub</AssemblyName>
    <RootNamespace>SavorHub</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Pages\Admin\Favorites\" />
    <Folder Include="wwwroot\images\menuItems\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="Stripe.net" Version="51.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Restaurant.Data\Restaurant.Data.csproj" />
    <ProjectReference Include="..\Restaurant.Utility\Restaurant.Utility.csproj" />
  </ItemGroup>

</Project>
